language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev


before_script:

script:
  # basic tests - command line tool installed and gives help/usage
  - ./sparkyEvents.py

branches:
  only:
    - master